Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

Outputs:
  S3BucketName:
    Value: !Ref MyS3Bucket

